Unicode should be working now.

I thought Python3 was supposed to be Unicode-compatible. Such naivete.
